# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: pvillaverde/radio_dixital
  tag: 1.4.5
  digest: ""
  pullPolicy: IfNotPresent
# LogLevel for all the tasks (Publishers & Subscribers)
logLevel: INFO
timeZone: Europe/Madrid
# Tasks executed in CronJobs (RefreshTasks)
cronJobs:
- task: refreshYoutube
  schedule: "15,45 * * * *"
- task: refreshPodcasts
  schedule: "0,30 * * * *"
- task: refreshBlogs
  schedule: "5,55 * * * *"
- task: refreshYoutubeStats
  schedule: "20 1 1,9,17,25 * *"
- task: refreshTwitchChannels
  schedule: "13 4 * * *"
- task: refreshTwitchGames
  schedule: "*/15 * * * *"
- task: refreshTwitchClips
  schedule: "0 5 * * 5" # Every Friday
- task: refreshTwitchStreams
  schedule: "* * * * *" # Every Minute
secretName: my-secret-config

nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}
# fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
