{{- range .Values.service.ports }}
apiVersion: gateway.networking.k8s.io/v1
kind: {{- if eq .protocol "UDP" }}UDPRoute{{- else }}TCPRoute{{- end }}
metadata:
  name: {{ include "common.fullname" . }}-{{ .name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs: {{- toYaml .gatewayParentRefs | nindent 4 }}
  rules:
  - backendRefs:
    - name: {{ include "common.fullname" . }}
      port: {{ .port }}
---
{{- end }}