
{{- range $v := .Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
   name: {{ $.Release.Name }}-{{ $v.task | kebabcase }}
spec:
   schedule: "{{ $v.schedule }}"
   concurrencyPolicy: Forbid
   jobTemplate:
      spec:
         template:
            spec:
               containers:
               - name: {{ $v.task | kebabcase }}    
                 securityContext: {{- toYaml $.Values.securityContext | nindent 19 }}      
                 image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"     
                 command: ["deno"]
                 args:
                 - task
                 - {{ $v.task}}
                 env:
                 - name: LOG_LEVEL
                   value: {{ $.Values.logLevel}}
                 - name: TZ
                   value: {{ $.Values.timeZone}}
                 volumeMounts:
                 - name: config-volume
                   mountPath: /opt/radio_dixital/src/config/
               restartPolicy: Never
               volumes:
               - name: config-volume
                 secret:
                   secretName: {{ $.Values.secretName}}
---
{{- end }}    