# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  registry: docker.io
  repository: pvillaverde/openttd-jgr
  tag: 1.0.68
  digest: ""
  pullPolicy: IfNotPresent

env:
- name: PUID
  value: "1000"
- name: PGID
  value: "3000"
- name: TZ
  value: Europe/Madrid
extraEnv: []
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

priorityClassName: ""
nodeSelector: {}
tolerations: {}

podSecurityContext:
  fsGroup: 3000
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: [ "NET_RAW" ]

backupJob:
  enabled: false
  schedule: "0 3 * * *"
  nfsServer: "" # Must be set to use BackupJob
  nfsShare: "" # Must be set to use BackupJob
  # force the overwrite of what is currently on the dataVolume with what it is in the backup.
  forceInitRsync: false

# If the image or the server downloads stuff that is not needed to backup but you dont want to download each time the pod is created.
gameFilesVolume:
  enabled: false
  size: 10Gi
  mounts:
  - mountPath: /game
dataVolume:
  size: 3Gi
  # Where the data volume will be mounted. Can be used with subPaths, but the whole volume will be backed up with the cronJob.
  mounts:
  - mountPath: /data
# extraVolumes for the container, i.e. if you want to mount config files or secrets.
extraVolumes: []
# extraVolumesMounts for the container, i.e. if you want to mount config files or secrets.
extraVolumesMounts: []

service:
  type: ClusterIP
  sessionAffinity: None
  ports: []
    # name: "game-udp"
    # port: "29070"
    # protocol: UDP
